#!/bin/sh

set -eu

readonly PDF="${1}"
readonly OUT="${2}"

pdfseparate "${PDF}" "${PDF}-%d"

for f in "${PDF}-"*
do
	size="$(pdftoppm "${f}" | hexdump | wc -l)"
	[ "${size}" -eq 6 ] && rm "${f}"
done

pdfunite "${PDF}-"* "${OUT}"
rm "${PDF}-"*
