title = "Valérian Rousset"
subtitle = "creative, logical, social"

profile = """\
	Software engineer (M.Sc. in computer science), result-oriented, used to
	fast-cycle projects, in any programming language, \
	with focus on code quality, modularity and standards compliance\
"""

[urls]
"valerian.rousset@proton.me" = "mailto:valerian.rousset@proton.me"
"github.com/tharvik" = "https://github.com/tharvik"
"linkedin.com/in/valerianrousset" = "https://linkedin.com/in/valerianrousset"

[competences]
_ = [
  "Strong skills in software design and coding",
  "Very fast understanding of concepts",
  "Team worker as well as autonomous",
  "Reliable and predictable",
  "Analytical and detail-oriented",
  "Deep understanding of computer systems",
]

["professional curriculum"]
"2025 …" = """\
	_LiGHT (Laboratory for Intelligent Global Health Technologies)_, systems specialist; \
	productionized medical machine learning platform; \
	used Typescript, Python, Next.js\
"""
"2024 …" = """\
	_MLO (Machine Learning and Optimization Laboratory)_, systems specialist; \
	structured decentralized and federated machine learning projects; \
	used Typescript, Docker, Vue.js\
"""
"2019 – 2023" = """\
	_C4DT (Center for Digital Trust)_, systems specialist; \
	brought projects from paper to production, creating reliable and usable programs out of research; \
	used Python, Rust, Typescript, Docker, Ansible; \
	participated in many open-source projects\
"""
"2018" = """\
	_ELCA Informatique SA_, trainee, master thesis; \
	built distributed and massively scalable load tester using cloud providers to uncover performance issues; \
	used Python, AMQP, Docker, Kubernetes, Terraform\
"""
"2016" = """\
	_Nagravision SA (Kudelski Security)_, trainee; \
	built vulnerability scanner aggregator to increase productivity of security specialists; \
	used Python, Celery, Elastic, Django; wrote own open-source libraries when needed\
"""

["diplomas"]
"2012 – 2018" = "_Bachelor_ & _Master_ in Computer Science, EPFL; grade: 5/6"

["computer science skills"]
"Languages" = """\
	_Rust_, _Typescript_, _go_, Python, \
	sh/bash, Scala, C/C++\
"""
"Technologies" = "_Docker_, _Vue.js_, _WebAssembly_, Grafana, Kubernetes, Next.js, Terraform"

[languages]
"Mother tongue" = "_French_, C2, native speaker"
"Foreign languages" = """\
	_English_, C1, fluent communication
	_German_, B1, understanding of basic discussions\
"""

[contact]
Address = "Avenue du Silo 34, 1020 Renens, Switzerland"
Telephone = "+41 77 463 50 14"
